#!/usr/bin/env python3
"""Stamp sponsor prices into advertise.html from data/pricing.json.

data/pricing.json is the only place a sponsor price lives.  This rewrites
the two price surfaces on advertise.html that must stay static (crawlers and
social cards don't run JS):
  - the rate-card <tbody>, between the BEGIN/END markers
  - the "from $N/mo" in the <head> meta descriptions, set to the lowest
    floor on the card so the teaser can never quote a price we don't offer
The rest of advertise.html is hand-written; only those spans are touched.
House ads (data/sponsors.json) read the same file at runtime via price_slot.

    python3 scripts/generate_advertise_pricing.py           # rewrite
    python3 scripts/generate_advertise_pricing.py --check   # exit 1 on drift
"""
from __future__ import annotations

import html
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PRICING_PATH = REPO_ROOT / "data" / "pricing.json"
OUT_PATH = REPO_ROOT / "advertise.html"

BEGIN = "<!-- BEGIN rate card: generated by scripts/generate_advertise_pricing.py from data/pricing.json -->"
END = "<!-- END rate card -->"
TEASER_RE = re.compile(r"([Ff]rom )\$\d+(/mo)")


def load_pricing() -> dict:
    p = json.loads(PRICING_PATH.read_text())
    for s in p["slots"]:
        # Reject anything that would print as "$None" or "$75.0".
        for k in ("from", "to"):
            if not isinstance(s[k], int) or s[k] <= 0:
                raise ValueError(f"pricing.json slot {s['key']!r}: {k} must be a positive integer")
        if s["from"] > s["to"]:
            raise ValueError(f"pricing.json slot {s['key']!r}: from > to")
    return p


def floor_price(p: dict) -> int:
    return min(s["from"] for s in p["slots"])


def _row(name: str, placement: str, targeting: str, price: str) -> str:
    e = lambda s: html.escape(s, quote=False)
    return (
        "      <tr>\n"
        f"        <td><b>{e(name)}</b></td>\n"
        f"        <td>{e(placement)}</td>\n"
        f"        <td>{e(targeting)}</td>\n"
        f'        <td class="price">{e(price)}</td>\n'
        "      </tr>\n"
    )


def rate_card_rows(p: dict) -> str:
    rows = [_row(s["name"], s["placement"], s["targeting"], f"${s['from']} – ${s['to']}")
            for s in p["slots"]]
    a = p["audience_uplift"]
    rows.append(_row(a["name"], a["placement"], a["targeting"], f"+ {a['pct']}% on top of base"))
    return "".join(rows)


def render(src: str, p: dict) -> str:
    start, end = src.find(BEGIN), src.find(END)
    if start < 0 or end < start:
        raise SystemExit(f"{OUT_PATH.name}: rate-card markers missing or out of order")
    src = src[:start + len(BEGIN)] + "\n" + rate_card_rows(p) + "      " + src[end:]

    head_end = src.find("<body")
    head, body = src[:head_end], src[head_end:]
    head, n = TEASER_RE.subn(rf"\g<1>${floor_price(p)}\g<2>", head)
    if n == 0:
        # A reworded teaser that drops the pattern would silently stop
        # tracking the card -- fail instead.
        raise SystemExit(f"{OUT_PATH.name}: no 'from $N/mo' teaser found in <head>")
    return head + body


def main() -> None:
    check = "--check" in sys.argv[1:]
    current = OUT_PATH.read_text()
    updated = render(current, load_pricing())
    if check:
        if updated != current:
            print(f"{OUT_PATH.name} is out of sync with data/pricing.json -- "
                  "run python3 scripts/generate_advertise_pricing.py", file=sys.stderr)
            sys.exit(1)
        print(f"{OUT_PATH.name} in sync with data/pricing.json")
        return
    if updated != current:
        OUT_PATH.write_text(updated)
        print(f"wrote {OUT_PATH.name} (floor ${floor_price(load_pricing())}/mo)")
    else:
        print(f"{OUT_PATH.name} already in sync")


if __name__ == "__main__":
    main()
